name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  adaptive_screen_utils: ^2.4.0
  camera: ^0.11.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_tesseract_ocr:
    path: lib/tesseract_ocr
  fluttertoast: ^9.0.0
  freezed_annotation: ^2.4.1  # ⬅️ annotation فقط في dependencies
  get_it: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.5.4
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  local_auth: ^3.0.0
  lottie: ^3.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1  # ⬅️ غيرها من 4.7.2
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.12.1

dev_dependencies:
  build_runner: ^2.4.13  # ⬅️ غيرها من 2.1.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5  # ⬅️ freezed في dev_dependencies فقط
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1  # ⬅️ شيلها من dependencies وحطها هنا

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/labels/
    - assets/models/
    - assets/tessdata/
    - assets/tessdata/ara.traineddata
    - assets/tessdata/eng.traineddata
    - assets/tessdata/ara_combined.traineddata
    - assets/tessdata/ara_number.traineddata
    - assets/tessdata_config.json

flutter_gen:
  output: lib/core/utils/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart